raw_data_columns:
  - feature_1
  - feature_2
  - feature_3
  - feature_4
  - feature_5

outliers_info:
  feature_1:
    upper_bound: 10
  feature_2:
    lower_bound: -5
  feature_3:
    lower_bound: 0
    upper_bound: 5